services:
  smart-shift:
    image: node:20-alpine
    container_name: smart-shift
    restart: unless-stopped
    working_dir: /app
    ports:
      - "3300:3000"
    volumes:
      - /DATA/AppData/smart-shift:/app
      - /DATA/AppData/smart-shift/data:/app/data
    command: ["sh", "-c", "npm install --omit=dev && node server.js"]